apiVersion: v1
kind: Pod
metadata:
  name: kubia-app
  labels:
    env: prod
    role: fronted
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: kubia-app
      image: httpd:latest
      ports:
        - containerPort: 8081
          protocol: TCP
  